version: '3'

networks:
  smart-reservation-network:
    driver: bridge

volumes:
  backend-logs:
  backend-static:

# 服务定义
services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: smart-reservation-redis
    ports:
      - "6379:6379"
    networks:
      - smart-reservation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-reservation-backend
    ports:
      - "8000:8000"
    networks:
      - smart-reservation-network
    depends_on:
      - redis
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/static:/app/static
    environment:
      - DATABASE_URL=sqlite:///./reservations.db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key-12345
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEVELOPMENT=true
      - DEBUG=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3