services:
  # Redis服务（仅Redis容器化）
  redis:
    image: redis:7-alpine
    container_name: smart-reservation-redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: smart-reservation-network